### PR TITLE
Added ThrowsException extension method and related tests.

### PR DESCRIPTION
**Pull request by camiller2**

### CODE REVIEW

**Comment by camiller2** [comment]
Added ThrowsException extension method and related tests.  This relates to #13 and #12.

**Comment by richardszalay** [comment]
Thanks for the PR. Two changes, if that's ok:

- Can you removed FluentAssertions? It seems excessive to introduce an assertions library for a single test
- Can you rename the extension method to "Throw" so it's more inline with "Respond" in language?

**Comment by richardszalay** [comment]
Excellent, thanks!

One last request: it looks like you used find/replace on "Throws", which has modified the comments for unrelated functionality. Could you change those back?

**Comment by camiller2** [comment]
Hmmmm...resharper was a bit overzealous it appears :-p I'll update and push. Good catch and thanks.

**Comment by richardszalay** [comment]
I've squashed those commits and merged. Thanks again for the PR!

**Pull request closed without merging**
