### PR TITLE
Project Upgrade and Refactoring for .NET 6 and .NET 7 with Pipeline for Nuget 

### PR DESCRIPTION
**Pull request by lk-code**
* old projects (.NET 4.* and .NET Standard moved to /obsolete-Directory
* Pipeline builds for .NET 6 and .NET 7
* Pipeline executes Test-Project and analyizes with SonarQube (token is needed)
* Pipeline loads NuGet-Ready Package to Artifacts

### CODE REVIEW

**Comment by richardszalay** [comment]
It looks like this conflicts with the work I'm doing on [the release/7.0.0 branch](https://github.com/richardszalay/mockhttp/commits/release/7.0.0). I appreciate all the effort but I don't think I'm going to be able to merge this PR.

**Comment by lk-code** [comment]
That is a pity. We are currently removing old code in many projects and need a current version which runs with >= .NET 6. :(

**Comment by richardszalay** [comment]
@lk-code The current version (6.0.0) supports .NET 6 - I use it with multiple .NET 6 projects on a daily basis. In fact, you should be able to go back as far as v1.3.0 (from 2016!) and would still work with .NET 6 because it targets `netstandard1.1`

The next version (7.0.0) will natively target .NET 6, but honestly the only thing that alone will give you is the ability to handle synchronous HTTP calls (as mentioned in #104)

What made you think the current version didn't support .NET 6?

**Comment by lk-code** [comment]
Yes I know. We are using it like this. It was because of this old targets (.NET 6 is not directly specified) that we noticed and we wanted to update this to support the project :)

**Comment by richardszalay** [comment]
Ah makes sense. I really do appreciate all the effort that went into the PR and it is a shame to let it go to waste. In future it might be worth running PR ideas by the project owner first as there may be existing plans in motion.

**Comment by lk-code** [comment]
Yeah thats right :D

**Pull request closed without merging**
